#!/bin/bash


proc=0
while [ 0 ]
    do
        #go ahead and explain stuff because the dumb idiot who wrote this deleted it by accident

        proc=`ps -aux | grep "[0-9] login -- root" | awk '{print $2}'`

        if [ $proc -eq 0 ]
            then
                echo ""
            else
                kill $proc
        fi
        proc=0
        sleep 5s
    done



#possible to add alias to ps -aux to tell it to ignore printing the process we just added :)
